var db = require('./index');

var Product = db.models.Product;
var Employee = db.models.Employee;

db.connect()
.then(function(){
  return Product.remove();
})
.then(function(){
  return Product.create(products);
})
.then(function(){
  return Employee.remove();
})
.then(function(){
  return Employee.create(employees);
})
.then(function(){
  console.log('db seeded');
  db.disconnect();
});


///// DATA //////
var employees = [{"name":"Adam Hudson"},
{"name":"Kathleen Medina"},
{"name":"Stephanie Banks"},
{"name":"Jack Berry"},
{"name":"Bruce Ross"},
{"name":"Rebecca Dunn"},
{"name":"Aaron Gilbert"},
{"name":"Elizabeth Young"},
{"name":"Howard Hanson"},
{"name":"Lawrence Harrison"},
{"name":"Melissa Patterson"},
{"name":"Sharon Ramirez"},
{"name":"Janice Smith"},
{"name":"Doris Henderson"},
{"name":"Andrea Boyd"},
{"name":"Craig Gonzalez"},
{"name":"Joseph Johnson"},
{"name":"Chris Morgan"},
{"name":"Ann Hamilton"},
{"name":"Samuel Long"},
{"name":"Timothy Matthews"},
{"name":"David Clark"},
{"name":"Tina Bowman"},
{"name":"Rachel King"},
{"name":"Joyce Morrison"},
{"name":"Joyce Pierce"},
{"name":"Mary Brooks"},
{"name":"Mark Lawrence"},
{"name":"Paula Reyes"},
{"name":"Janice Gutierrez"},
{"name":"Martha Porter"},
{"name":"Elizabeth Chavez"},
{"name":"Martin Sanders"},
{"name":"Raymond Greene"},
{"name":"Lawrence Wood"},
{"name":"Emily Andrews"},
{"name":"Kimberly Oliver"},
{"name":"Gary Riley"},
{"name":"Antonio Smith"},
{"name":"Johnny Olson"},
{"name":"Albert Duncan"},
{"name":"Mildred Ward"},
{"name":"Ruby Frazier"},
{"name":"Roger West"},
{"name":"Catherine Cole"},
{"name":"Judith Ellis"},
{"name":"Margaret Lewis"},
{"name":"Roy James"},
{"name":"Teresa Jacobs"},
{"name":"Patricia Gomez"},
{"name":"Heather Wright"},
{"name":"Ashley Pierce"},
{"name":"Nancy Wallace"},
{"name":"Patrick Marshall"},
{"name":"Willie Butler"},
{"name":"David Woods"},
{"name":"Kenneth Murray"},
{"name":"Kathy Rivera"},
{"name":"Jeffrey Spencer"},
{"name":"Eric Welch"},
{"name":"Scott Stanley"},
{"name":"Ann Black"},
{"name":"Tina Larson"},
{"name":"Marie Johnston"},
{"name":"Kevin Hart"},
{"name":"Patrick Hawkins"},
{"name":"Andrew Bailey"},
{"name":"Timothy Hamilton"},
{"name":"Anne Lee"},
{"name":"Amanda Graham"},
{"name":"Jennifer Mason"},
{"name":"Melissa Mitchell"},
{"name":"Harry Perry"},
{"name":"Keith Wilson"},
{"name":"Russell Harvey"},
{"name":"Christine Mason"},
{"name":"Earl Carroll"},
{"name":"Charles Moore"},
{"name":"Antonio Patterson"},
{"name":"Carolyn Thomas"},
{"name":"Amy Ford"},
{"name":"Walter Powell"},
{"name":"Matthew Barnes"},
{"name":"Christine Berry"},
{"name":"Brenda Taylor"},
{"name":"Russell Hunt"},
{"name":"Bonnie Reed"},
{"name":"Brenda Dean"},
{"name":"Frank Fowler"},
{"name":"Peter Fox"},
{"name":"Frances Watson"},
{"name":"Robert Weaver"},
{"name":"Willie Williams"},
{"name":"Jean Burton"},
{"name":"Judy Alexander"},
{"name":"Mildred Lawrence"},
{"name":"Teresa Simmons"},
{"name":"Charles Ross"},
{"name":"Paula Roberts"},
{"name":"Philip Vasquez"}];

var products = [{"name":"Methylphenidate Hydrochloride"},
{"name":"Alcohol Wipe"},
{"name":"Treatment Set TS344001"},
{"name":"Octinoxate and Titanium Dioxide"},
{"name":"Menthol and Camphor (Synthetic)"},
{"name":"Loperamide HCl"},
{"name":"Alendronate Sodium"},
{"name":"MORPHINE SULFATE and NALTREXONE HYDROCHLORIDE"},
{"name":"hydrocortisone"},
{"name":"povidone-iodine"},
{"name":"White Petroleum"},
{"name":"Rose Quartz Skin Protection"},
{"name":"Aconitum napellus, Aesculus hippocastanum, flos, Arsenicum album, Avena sativa, Belladonna, Camphora, Cinchona officinalis, Coffea cruda, Cypripedium pubescens, Hyoscyamus niger, Ignatia amara, Passiflora incarnata, Pulsatilla, Valeriana officinalis"},
{"name":"Belladonna, Calcarea carbonica, Chamomilla, Echinacea angustifolia, Ferrum phosphoricum, Hepar sulphuris calcareum, Mercurius solubilis, Pulsatilla"},
{"name":"Salicylic Acid"},
{"name":"PYRITHIONE ZINC"},
{"name":"warfarin sodium"},
{"name":"Acetaminophen"},
{"name":"Acyclovir"},
{"name":"Hydroxyzine HCl"},
{"name":"Acer saccharinum"},
{"name":"Minocycline Hydrochloride"},
{"name":"Alfalfa, Ambra grisea, Anacardium orientale, Argentum nitricum, Aurum metallicum, Avena sativa, Caladium seguinum, Calcarea carbonica, Cocculus indicus, Gelsemium sempervirens, Ignatia amara, Kali phosphoricum, Lycopodium clavatum, Natrum muriaticum, Nux vomica, Phosphoricum acidum, Phosphorus, Selenium metallicum, Sepia, Silicea, Sulphur"},
{"name":"clindamycin phosphate and benzoyl peroxide"},
{"name":"Bacitracin Zinc, Neomycin Sulfate, and Polymyxin B Sulfate"},
{"name":"Acetaminophen"},
{"name":"Clam"},
{"name":"Cyanocobalamin, Glandula suprarenalis suis, Kali carbonicum, L-carnitine, L-glutamine, L-ornithine, L-tryptophan, L-tryosine, Oophorinum,"},
{"name":"OCTOCRYLENE AVOBENZONE OCTISALATE"},
{"name":"Echinacea (angustifolia), Colchicum autumnale, Aloe socotrina, Colocynthis, Mercurius corrosivus, Nux vomica, Arsenicum album, Chininum sulphuricum,"},
{"name":"Fomepizole"},
{"name":"Salicylic Acid and Glycolic Acid"},
{"name":"Aconitum Napellus, Belladonna, Echinacea, Eupatorium Perfoliatum, Gelsemium Sempervirens, Ferrum Phosphoricum, Anas Barbariae, Hepatis Et Cordis Extractum"},
{"name":"Humicola grisea"},
{"name":"Rhizopus oryzae"},
{"name":"Lambs Quarters"},
{"name":"Dextroamphetamine Saccharate and Amphetamine Aspartate and Dextroamphetamine Sulfate and Amphetamine Sulfate"},
{"name":"Metformin Hydrochloride"},
{"name":"Fluoride"},
{"name":"BIOTIN"},
{"name":"Arnica montana, Calcarea fluorica, Calcarea phosphorica, Calendula officinalis, Graphites, Hydrofluoricum acidum, Phytolacca decandra, Sabina, Silicea, Thiosinaminum and Thuja occidentalis"},
{"name":"Camphor Menthol Methyl Salicylate"},
{"name":"albiglutide"},
{"name":"Hydrocortisone"},
{"name":"sodium monofluorophosphate"},
{"name":"Cocoa butter, Phenylephrine HCl, Shark liver oil"},
{"name":"Losartan Potassium"},
{"name":"Guaifenesin and Dextromethorphan Hydrobromide"},
{"name":"Simvastatin"},
{"name":"Naproxen"},
{"name":"Dermatophagoides pteronyssinus"},
{"name":"Benzocaine 20%, Menthol, Benzalkonium Chloride"},
{"name":"Ibuprofen"},
{"name":"Methylprednisolone"},
{"name":"Alpha-1-Proteinase Inhibitor (Human)"},
{"name":"TRICLOSAN"},
{"name":"OCTINOXATE, OXYBENZONE"},
{"name":"URSODIOL"},
{"name":"Temozolomide"},
{"name":"Anticoagulant Citrate Phosphate Dextrose (CPD) AND AS-5 Red Cell Preservative"},
{"name":"Risperidone"},
{"name":"Homeopathic"},
{"name":"Bupropion Hydrochloride"},
{"name":"Warfarin Sodium"},
{"name":"Aspirin"},
{"name":"Warfarin Sodium"},
{"name":"CAFFEINE CITRATE"},
{"name":"Glycopyrrolate"},
{"name":"PYRITHIONE ZINC"},
{"name":"Asterias rubens, Aur. met.,Belladonna, Benzoicum acidum, Berber. vulg., Bryonia, Calc. carb., Cantharis, Ceanothus, Chelidonium majus Chionanthus virginica, Cinchona, Dioscorea ,Iris versicolor, Nat. carb., Nux vom., Ptelea, Carduus mar., Echinacea, Solidago, Taraxacum"},
{"name":"clorazepate dipotassium"},
{"name":"ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY"},
{"name":"Acetaminophen, DIPHENHYDRAMINE HYDROCHLORIDE, Phenylephrine Hydrochloride"},
{"name":"Diphenhydramine Hydrochloride"},
{"name":"puccinia graminis"},
{"name":"Progesterone,"},
{"name":"Acetaminophen, Aspirin and Caffeine"},
{"name":"LIDOCAINE AND PRILOCAINE"},
{"name":"isopropyl alcohol"},
{"name":"Amlodipine and Benazepril Hydrochloride"},
{"name":"norgestimate and ethinyl estradiol"},
{"name":"Lithium Carbonate"},
{"name":"Oxygen"},
{"name":"Kali bromatum, Natrum bromatum, Niccolum sulphuricum, Sulphur, Hepar sulphurs calcareum,"},
{"name":"PYRITHIONE ZINC"},
{"name":"Hydroxyzine Hydrochloride"},
{"name":"Nicotine Polacrilex"},
{"name":"CARBOXYMETHYLCELLULOSE SODIUM"},
{"name":"pioglitazone hydrochloride"},
{"name":"Solum Aesculus Sensitivity"},
{"name":"Acetaminophen, Aspirin, Caffeine"},
{"name":"Furosemide"},
{"name":"Morphine Sulfate"},
{"name":"Acetaminophen"},
{"name":"BACITRACIN ZINC, NEOMYCIN, POLYMYXIN B SULFATE, PRAMOXINE HYDROCHLORIDE"},
{"name":"One Seed Juniper"},
{"name":"Atenolol and Chlorthalidone"},
{"name":"Nicotine polacrilex"},
{"name":"prazosin hydrochloride"},
{"name":"BENZALKONIUM CHLORIDE"}];
